### ISSUE TITLE
Support newer dependencies

### ISSUE THREAD

**Issue by zoechi** [dart-lang/appengine#45]
- gcloud: '>=0.1.2 <0.3.0' ==> 0.3.3

**Comment by sgjesse** [comment]
The latest version (just published) of the [gcloud](https://pub.dartlang.org/packages/gcloud) package is `0.2.0+12`, so `>=0.1.2 <0.3.0` should be OK here.

**Comment by zoechi** [comment]
Thanks a lot :+1:

**Comment by zoechi** [comment]
I can't use

```yaml
dependencies:
  appengine: ^0.3.3
  googleapis_beta: ^0.25.0
```

> Package gcloud has no versions that match >=0.1.2 <0.3.0 derived from:
- appengine 0.3.3 depends on version >=0.1.2 <0.3.0
